name: Security audit

# Define permissions at the workflow level
permissions:
  issues: write # For creating issues
  checks: write # For creating check runs
  contents: read

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-audit
        run: cargo binstall cargo-audit -y
      - uses: aderinom/audit-check@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          new-issue-labels: "security, triage-required"
